name: Create Release on Pushed Tag

on:
  # workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get previous tag
        id: prev_tag
        run: echo "tag=$(git describe --abbrev=0 --tags HEAD~1)" >> $GITHUB_OUTPUT

      - name: Get commit titles since previous tag
        id: commit_titles
        run: |
          {
            echo "lines<<EOF"
            echo $(git --no-pager log --pretty=format:'- %s' ${{ steps.prev_tag.outputs.tag }}..HEAD~1)
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ### Changes since last release:
            ${{ steps.commit_titles.outputs.lines }}
          draft: false
          prerelease: false

