name: Workflow2

on:
  workflow_run:
    workflows: [Workflow1]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow_run.conclusion
        run: echo "Conclusion=${{ github.event.workflow_run.conclusion == 'success' }}"
