name: Workflow1

on:
  # push:
  #   tags: ['*']
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print info
        run: echo ${{ github.ref }}
