name: Workflow2

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_run:
    workflows: [Workflow1]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo "Conclusion=${{ github.event.workflow_run.conclusion }}"
          echo "Release=${{ github.event.release }}"
          echo "Workflow=${{ github.event.workflow }}"
